spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:fimo;MODE=MySQL;NON_KEYWORDS=trading
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
